redis:
    build: ./redis
    expose:
        - "6379"
    ports:
        - "6379:6379"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

mysql:
    build: ./mysql
    expose:
        - "3306"
    # ports:
    #     - "3306:3306"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb
        # - MYSQL_HOST=localhostx
        # - MYSQL_USER=guestx
        # - MYSQL_PASS=guestx

cakephp:
    build: ./cakephp
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - mysql
        - redis
        - scala
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

scala:
    build: ./scala
    expose:
        - "1234"
    ports:
        - "1234:1234"
    links:
        - mysql
        - redis
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

datastorage:
    build: ./data
    volumes:
        - /var/lib/mysql/
        - /usr/share/nginx/html/
        - /var/lib/redis/
        - /var/lib/mls/
    environment:
        - TERM=dumb



