redis:
    build: ./redis
    expose:
        - "6379"
    ports:
        - "6379:6379"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

mysql:
    build: ./mysql
    expose:
        - "3306"
    ports:
        - "3306:3306"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb
        - MYSQL_HOST=127.0.0.1
        - MYSQL_USER=root
        - MYSQL_PASS=Shanghai!1

cakephp:
    build: ./cakephp
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - mysql
        - redis
        - scala
        # - search
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

scala:
    build: ./scala
    expose:
        - "1234"
    ports:
        - "1234:1234"
    links:
        - mysql
        - redis
        # - search
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

search:
    build: ./search
    expose:
        - "9200"
        - "9300"
    ports:
        - "9200:9200"
        - "9300:9300"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb


datastorage:
    build: ./data
    volumes:
        - $HOME/Data/mls/logs/nginx/:/var/log/nginx/
        - $HOME/Data/mls/logs/php-fpm/:/var/log/php-fpm/
        - $HOME/Data/mls/logs/redis/:/var/log/redis/
        - $HOME/Data/mls/logs/mysql/:/var/log/mysql/
        - $HOME/Data/mls/logs/elasticsearch/:/var/log/elasticsearch/
        - $HOME/Data/mls/data/elasticsearch/:/var/lib/elasticsearch/
        - $HOME/Data/mls/data/mysql/:/var/lib/mysql/
        - $HOME/Data/mls/data/redis/:/var/lib/redis/
        - $HOME/Public:/usr/share/nginx/html/
        - $HOME/Public/mls:/var/lib/mls/
    environment:
        - TERM=dumb



