redis:
    build: ./redis
    expose:
        - "6379"
    ports:
        - "6379:6379"
    environment:
        - TERM=dumb

mysql:
    build: ./mysql
    expose:
        - "3306"
    ports:
        - "3306:3306"
    environment:
        - TERM=dumb

cakephp:
    build: ./cakephp
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - mysql
        - redis
        - scala
    environment:
        - TERM=dumb

scala:
    build: ./scala
    expose:
        - "1234"
    ports:
        - "1234:1234"
    links:
        - mysql
        - redis
    environment:
        - TERM=dumb


