
zabbix:
    build: ./zabbix
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - mysql:mysql
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

mysql:
    build: ./mysql
    expose:
        - "3306"
    ports:
        - "3306:3306"
    # links:
    #     - zabbix:offit
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

datastorage:
    build: ./data
    volumes:
        - $HOME/Data/mls/logs/mysql/:/var/log/mysql/
        - $HOME/Data/mls/data/mysql/:/var/lib/mysql/
        - /etc/localtime:/etc/localtime:ro
        - $HOME/Data/zabbix/conf/zabbix.conf.php:/etc/zabbix/web/zabbix.conf.php
    environment:
        - TERM=dumb



