zabbix:
    build: ./zabbix
    expose:
        - "80"
    ports:
        - "80:80"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

datastorage:
    build: ./data
    volumes:
        - $HOME/Data/mls/logs/nginx/:/var/log/nginx/
        - $HOME/Data/mls/logs/php-fpm/:/var/log/php-fpm/
        - $HOME/Data/mls/logs/mysql/:/var/log/mysql/
        - $HOME/Data/mls/data/mysql/:/var/lib/mysql/
        - $HOME/Data/mls/data/media/:/data/files/media/
        - $HOME/Data/mls/data/redis/:/var/lib/redis/
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TERM=dumb



