zabbix:
    build: ./zabbix
    expose:
        - "80"
        - "3306"
    ports:
        - "80:80"
        - "3306:3306"
    volumes_from:
        - datastorage
    environment:
        - TERM=dumb

datastorage:
    build: ./data
    volumes:
        - $HOME/Data/mls/logs/mysql/:/var/log/mysql/
        - $HOME/Data/mls/data/mysql/:/var/lib/mysql/
        - /etc/localtime:/etc/localtime:ro
    environment:
        - TERM=dumb



