hub:
    build: ./hub
    expose:
        - "5000"
    ports:
        - "5000:5000"
    volumes_from:
        - data
    environment:
        - DOCKER_REGISTRY_CONFIG=/registry-conf/config.yml
        - SETTINGS_FLAVOR=local
        - STORAGE_PATH=/tmp/registry
        - TERM=dumb

nginx:
    build: ./nginx
    expose:
        - "433"
        - "80"
    ports:
        - "433:433"
        - "80:80"
    volumes_from:
        - data
    environment:
        - TERM=dumb


data:
    build: ./data
    volumes:
        - $HOME/Data/registry/registry-conf/:/registry-conf/
        - $HOME/Data/registry/tmp/registry/:/tmp/registry/
    environment:
        - TERM=dumb



