mysql:
    build: ./mysql
    expose:
        - "3306"
    # ports:
    #    - "3306:3306"
    volumes_from:
        - data
    environment:
        - TERM=dumb
        - MYSQL_HOST=localhost
        - MYSQL_USER=root
        - MYSQL_PASS=Shanghai!1

mjq:
    build: ./mjq
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - mysql
    volumes_from:
        - data
    environment:
        - TERM=dumb

data:
    build: ./data
    volumes:
        - $HOME/Data/mjq/logs/nginx/:/var/log/nginx/
        - $HOME/Data/mjq/logs/php-fpm/:/var/log/php-fpm/
        - $HOME/Data/mjq/logs/mysql/:/var/log/mysql/
        - $HOME/Data/mjq/data/mysql/:/var/lib/mysql/
        - $HOME/Public/jobs/meijiequan/public/:/usr/share/nginx/html/
        - $HOME/Public/jobs/meijiequan/:/usr/share/nginx/
    environment:
        - TERM=dumb



