version: '3'
services:

    mysql:
        build: ./mysql
        expose:
            - "3306"
        ports:
            - "3307:3306"
        dns:
            - 8.8.8.8
        dns_search:
            - 8.8.8.8
        volumes:
            - data-volume:/var/log/mysql/
            - data-volume:/var/lib/mysql/
        environment:
            - TERM=dumb

    namenode:
        build: ./namenode
        expose:
            - "22"
        ports:
            - "222:22"
        # volumes
        #     - data-volume:/opt/data/
        links:
            - mysql:db
        environment:
            - TERM=dumb

    # datanode:
    #     build: ./datanode
    #     expose:
    #         - "22"
    #     ports:
    #         - "223:22"
    #     # volumes
    #     #     - data-volume:/opt/data/
    #     # deploy:
    #     #     mode: replicated
    #     #     replicas: 2
    #     links:
    #         - namenode:master
    #         - mysql:db

    #     environment:
    #         - TERM=dumb

volumes:
    data-volume:
        
    # volumes:
    #     - $HOME/Data/mls/logs/redis/:/var/log/redis/
    #     - $HOME/Data/mls/logs/mysql/:/var/log/mysql/
    #     - $HOME/Data/mls/data/mysql/:/var/lib/mysql/
    #     - /etc/localtime:/etc/localtime:ro
    # environment:
    #     - TERM=dumb
    



