FROM fedora
MAINTAINER Eric King <jinqiqiqi@gamil.com>


#RUN ["dnf", "clean", "all"]
#RUN ["dnf", "-y", "update"]
RUN ["dnf", "install", "-y", "rabbitmq-server", "telnet", "coreutils", "procps"]
RUN ["dnf", "clean", "all"]


