redis:
    build: ./redis
    expose:
        - "6379"
    ports:
        - "6379:6379"
    volumes_from:
        - data
    environment:
        - TERM=dumb


mysql:
    build: ./mysql
    expose:
        - "3306"
    ports:
        - "3306:3306"
    volumes_from:
        - data
    environment:
        - TERM=dumb
        - MYSQL_HOST=127.0.0.1
        - MYSQL_USER=root
        - MYSQL_PASS=pass


php:
    build: ./php
    expose:
        - "80"
    ports:
        - "80:80"
    links:
        - mysql
        - redis
    volumes_from:
        - data
    environment:
        - TERM=dumb


data:
    build: ./data
    volumes:
        - $HOME/Data/devel/logs/nginx/:/var/log/nginx/
        - $HOME/Data/devel/logs/php-fpm/:/var/log/php-fpm/
        - $HOME/Data/devel/logs/redis/:/var/log/redis/
        - $HOME/Data/devel/logs/mysql/:/var/log/mysql/
        - $HOME/Data/devel/data/mysql/:/var/lib/mysql/
        - $HOME/Data/devel/data/redis/:/var/lib/redis/
        - $HOME/Public:/usr/share/nginx/html/
        - ./php/conf/conf.d/:/etc/nginx/conf.d/
    environment:
        - TERM=dumb
